import { useState } from 'react'

const shuffle = <T,>(items: readonly T[]) => [...items].sort(() => Math.random() - 0.5)

type Finding = { id: string; title: string; isBug: boolean; explanation: string }
type Challenge = { label: string; level: string; title: string; brief: string; actions: Array<[string, string]>; findings: Finding[] }

const challenges: Challenge[] = [
  { label: '05 · PASSWORD RECOVERY', level: 'INTERMEDIATE', title: 'Recover an account without creating new risk.', brief: 'Investigate this password-reset flow. Review its messages, attempt a reset, and compare the behavior with what users should expect from a secure recovery journey.', actions: [['Request unknown email', 'The page says: “No account exists for that email address.”'], ['Use expired reset link', 'The link opens the password form and allows a new password to be saved.'], ['Submit reset twice', 'Two reset emails are sent within seconds.'], ['Try a weak password', 'The form accepts “password” with no requirements or guidance.']], findings: [{ id: 'enumeration', title: 'Reset message reveals whether an account exists', isBug: true, explanation: 'Recovery messages should avoid exposing account existence because that can support account enumeration.' }, { id: 'expired', title: 'Expired reset link can still change the password', isBug: true, explanation: 'A reset token needs a valid expiration and should be rejected after it expires.' }, { id: 'duplicate-email', title: 'Repeated reset requests create duplicate emails', isBug: true, explanation: 'The flow should protect against duplicate sends and provide clear retry behavior.' }, { id: 'password-guidance', title: 'Password reset accepts weak credentials without guidance', isBug: true, explanation: 'Requirements and useful validation feedback are needed before the password is accepted.' }, { id: 'email-delay', title: 'Reset email arrives after a few seconds', isBug: false, explanation: 'A brief delivery delay alone is not a defect unless it violates a stated service expectation.' }] },
  { label: '06 · PAYMENT INCIDENT', level: 'ADVANCED', title: 'Trace the incident, not just the symptom.', brief: 'A feature-flag rollout is live in multiple regions. Use the evidence trail to decide what blocks release, what is a symptom, and what does not require escalation.', actions: [['Review EU checkout', 'The UI says “Payment failed,” but the payment service response is 201 Authorized.'], ['Retry after timeout', 'The second attempt produces a second authorization with the same customer and cart ID.'], ['Compare feature flags', 'EU has the new checkout flag enabled, but a cached response serves the old flag for some sessions.'], ['Open accessibility fallback', 'The fallback payment dialog opens with focus behind the modal.']], findings: [{ id: 'false-failure', title: 'Successful payment is presented as a failed payment', isBug: true, explanation: 'The UI and service state disagree, which can cause duplicate attempts and customer confusion.' }, { id: 'duplicate-charge', title: 'Retry after timeout creates a second authorization', isBug: true, explanation: 'The payment workflow needs idempotency to prevent duplicate charges during uncertain network outcomes.' }, { id: 'flag-cache', title: 'Feature flag is cached inconsistently across sessions', isBug: true, explanation: 'Inconsistent rollout state creates unreliable behavior and makes incident investigation harder.' }, { id: 'modal-focus', title: 'Fallback payment dialog leaves keyboard focus behind the modal', isBug: true, explanation: 'A modal must manage focus so keyboard and assistive-technology users can complete or exit the flow.' }, { id: 'healthy-api', title: 'Payment API returns a successful response', isBug: false, explanation: 'This is evidence, not a defect by itself. The problem is the mismatch between payment success and the customer-facing result.' }] },
]

export function AdvancedBugHunts() {
  const [active, setActive] = useState(0)
  const [evidence, setEvidence] = useState<number[]>([])
  const [reported, setReported] = useState<string[]>([])
  const challenge = challenges[active]
  const [findingOrder, setFindingOrder] = useState(() => shuffle(challenge.findings))
  const trueFindings = challenge.findings.filter((finding) => finding.isBug)
  const found = reported.filter((id) => challenge.findings.find((finding) => finding.id === id)?.isBug).length
  const chooseChallenge = (index: number) => { setActive(index); setEvidence([]); setReported([]); setFindingOrder(shuffle(challenges[index].findings)) }
  return <section className="advanced-hunts"><div className="advanced-hunt-tabs">{challenges.map((item, index) => <button type="button" key={item.label} className={active === index ? 'active' : ''} onClick={() => chooseChallenge(index)}>{item.label}</button>)}</div><div className="advanced-hunt-header"><p className="eyebrow">{challenge.level} BUG HUNT</p><h3>{challenge.title}</h3><p>{challenge.brief}</p></div><div className="advanced-hunt-grid"><div className="evidence-panel"><p className="eyebrow">INVESTIGATE</p>{challenge.actions.map(([action, result], index) => <article key={action}><button type="button" onClick={() => setEvidence((current) => current.includes(index) ? current : [...current, index])}>{action} <span>↗</span></button>{evidence.includes(index) && <p>{result}</p>}</article>)}</div><div className="finding-panel"><p className="eyebrow">LOG FINDINGS · {found}/{trueFindings.length}</p>{findingOrder.map((finding) => <button type="button" key={finding.id} className={reported.includes(finding.id) ? (finding.isBug ? 'reported' : 'guess') : ''} onClick={() => setReported((current) => current.includes(finding.id) ? current : [...current, finding.id])}><span>{reported.includes(finding.id) ? (finding.isBug ? 'FOUND' : 'NOT A DEFECT') : 'LOG'}</span><b>{finding.title}</b>{reported.includes(finding.id) && <small>{finding.explanation}</small>}</button>)}</div></div></section>
}
