import { useState } from 'react'
import { Logo } from './Logo'
import { ThemeToggle } from './ThemeToggle'

type ExampleLine = { text: string; kind: 'request' | 'context' | 'response' | 'payload' | 'assertion'; hint: string }

const lessons: Array<{ number: string; label: string; title: string; copy: string; points: string[]; example: ExampleLine[] }> = [
  { number: '01', label: 'Start here', title: 'What API testing is really checking.', copy: 'API testing checks how systems exchange data—not just whether a screen looks correct. A strong check considers the request, the response, the rules around data, and what happens when something goes wrong.', points: ['A request asks a service to do something.', 'A response communicates the result.', 'Your test verifies the contract between the two.'], example: [{ text: 'GET /api/customers/42', kind: 'request', hint: 'Request: method + route' }, { text: '200 OK', kind: 'response', hint: 'Response: HTTP status' }, { text: '{ "id": 42, "name": "Jordan Ellis" }', kind: 'payload', hint: 'Payload: returned data' }] },
  { number: '02', label: 'Build requests', title: 'Understand the parts of a request.', copy: 'Every request gives the server context. Start by identifying the method, route, headers, query values, and body—then vary one thing at a time to learn what each part controls.', points: ['Method: GET, POST, PUT, PATCH, or DELETE.', 'Route and parameters identify the target.', 'Headers and body carry context and data.'], example: [{ text: 'POST /api/orders?region=eu', kind: 'request', hint: 'Request: method, route, and query parameter' }, { text: 'Content-Type: application/json', kind: 'context', hint: 'Context: request header' }, { text: '{ "productId": "headphones", "quantity": 1 }', kind: 'payload', hint: 'Payload: request body' }] },
  { number: '03', label: 'Read responses', title: 'A status code is only the first clue.', copy: 'A response can look successful while still containing the wrong data, missing fields, or unsafe information. Pair the status code with body, headers, and the observable outcome.', points: ['Confirm the expected status code.', 'Check the response body and data types.', 'Verify useful error messages and safe failure behavior.'], example: [{ text: '201 Created', kind: 'response', hint: 'Response: HTTP status' }, { text: 'Location: /api/orders/913', kind: 'context', hint: 'Context: response header' }, { text: '{ "orderId": 913, "status": "pending" }', kind: 'payload', hint: 'Payload: response body' }] },
  { number: '04', label: 'Validate', title: 'Check the contract, not only one value.', copy: 'Validation means confirming that a response has the right shape and meaning. Compare required fields, types, allowed values, and business rules—not just a sample response.', points: ['Required: id, email, role.', 'Types: id is a number; email is a string.', 'Rules: a customer cannot access an admin-only route.'], example: [{ text: 'expect(status).toBe(200)', kind: 'assertion', hint: 'Assertion: expected status' }, { text: 'expect(body.email).toMatch(/@/)', kind: 'assertion', hint: 'Assertion: value format' }, { text: 'expect(body.role).not.toBe("admin")', kind: 'assertion', hint: 'Assertion: access rule' }] },
  { number: '05', label: 'Protect access', title: 'Authentication proves identity. Authorization controls access.', copy: 'Testing a valid token is not enough. Compare what different users can do, what expired credentials receive, and whether sensitive data is protected in error states.', points: ['No token should receive a safe 401 response.', 'A valid user may still be denied a restricted action.', 'Expired or altered tokens should fail predictably.'], example: [{ text: 'GET /api/admin/reports', kind: 'request', hint: 'Request: restricted route' }, { text: 'Authorization: Bearer <expired-token>', kind: 'context', hint: 'Context: authentication header' }, { text: '401 Unauthorized', kind: 'response', hint: 'Response: expected denial' }] },
  { number: '06', label: 'Handle failure', title: 'Useful API tests include difficult conditions.', copy: 'High-value API coverage explores missing data, duplicate submissions, dependency failures, slow responses, and retries. The aim is to make failures understandable and safe.', points: ['Send invalid and boundary values.', 'Retry a request that may have partially completed.', 'Verify errors do not expose internal details.'], example: [{ text: 'POST /api/payments', kind: 'request', hint: 'Request: payment submission' }, { text: 'Idempotency-Key: checkout-184', kind: 'context', hint: 'Context: duplicate-request protection' }, { text: '409 Conflict or one safe payment result', kind: 'response', hint: 'Response: safe retry outcome' }] },
]

export function ApiTestingGuide({ onBack, theme, onToggleTheme }: { onBack: () => void; theme: 'light' | 'dark'; onToggleTheme: () => void }) {
  const [activeIndex, setActiveIndex] = useState(0)
  const lesson = lessons[activeIndex]

  return <main className="api-guide-hub" id="top" tabIndex={-1}>
    <header className="learn-hub-nav"><Logo onHome={onBack} /><div className="hub-nav-actions"><ThemeToggle theme={theme} onToggle={onToggleTheme} /><button type="button" onClick={onBack}>← Back to Learn</button></div></header>
    <section className="api-guide-hero"><p className="eyebrow">API TESTING FIELD GUIDE</p><h1>Understand the<br /><em>conversation.</em></h1><p>A practical, original guide to testing requests, responses, access, and failure behavior—one focused lesson at a time.</p></section>
    <section className="api-guide-main" aria-label="API testing lessons"><aside className="api-guide-tabs" role="tablist" aria-label="API testing topics">{lessons.map((item, index) => <button type="button" key={item.label} className={activeIndex === index ? 'active' : ''} onClick={() => setActiveIndex(index)} role="tab" aria-selected={activeIndex === index}><span>{item.number}</span>{item.label}<b>↗</b></button>)}</aside><article className="api-guide-lesson" aria-live="polite"><p className="eyebrow">{lesson.number} · {lesson.label.toUpperCase()}</p><h2>{lesson.title}</h2><p>{lesson.copy}</p><ul>{lesson.points.map((point) => <li key={point}>{point}</li>)}</ul><div className="api-guide-example"><div className="api-example-heading"><p className="eyebrow">EXAMPLE</p><span>Hover a line to identify it.</span></div>{lesson.example.map((line) => <code key={line.text} className={`api-code-${line.kind}`} title={line.hint}><span>{line.kind}</span>{line.text}</code>)}</div><div className="api-guide-controls"><button type="button" disabled={activeIndex === 0} onClick={() => setActiveIndex((index) => index - 1)}>← Previous</button><button type="button" disabled={activeIndex === lessons.length - 1} onClick={() => setActiveIndex((index) => index + 1)}>Next lesson →</button></div></article></section>
    <section className="api-guide-checklist"><p className="eyebrow">A SIMPLE STARTING CHECKLIST</p><h2>Before calling an API check,<br /><em>ask better questions.</em></h2><div>{['What user or system need does this route support?', 'What should happen with invalid, missing, or duplicate input?', 'What response confirms success—and what evidence confirms safety?', 'Which user roles should be allowed or denied?'].map((item, index) => <p key={item}><span>{String(index + 1).padStart(2, '0')}</span>{item}</p>)}</div></section>
  </main>
}
