import { useState } from 'react'

const shuffle = <T,>(items: readonly T[]) => [...items].sort(() => Math.random() - 0.5)

const challenges = [
  { label: 'PLAYWRIGHT · LOCATORS', title: 'The test fails when the button text changes.', error: 'Error: locator("text=Continue") did not resolve', code: `await page.getByText('Continue').click()`, choices: [['Use a role-based locator with its accessible name.', true, `await page.getByRole('button', { name: 'Continue to payment' }).click()`], ['Add a five-second wait before clicking.', false, 'A fixed wait hides timing symptoms but does not make the locator more reliable.'], ['Click the first button on the page.', false, 'This may pass now, but it removes the test’s connection to the intended behavior.']] },
  { label: 'PLAYWRIGHT · ASYNC', title: 'The assertion occasionally passes before the page updates.', error: 'Expected confirmation heading was not visible', code: `expect(page.getByRole('heading', { name: 'Order confirmed' })).toBeVisible()`, choices: [['Await the asynchronous assertion.', true, `await expect(page.getByRole('heading', { name: 'Order confirmed' })).toBeVisible()`], ['Retry the whole test three times.', false, 'Retries can be useful diagnostics, but they should not replace waiting for the expected behavior.'], ['Replace the assertion with a screenshot.', false, 'A screenshot can help investigate, but it is not a reliable behavior assertion.']] },
  { label: 'API · ASSERTIONS', title: 'The API check passes even when the response has the wrong status.', error: 'Response body contains an id, but the endpoint returns 500', code: `expect(response.body.id).toBeTruthy()`, choices: [['Assert the response status before the body contract.', true, `expect(response.status).toBe(201)\nexpect(response.body.id).toBeTruthy()`], ['Only assert that the response body is not empty.', false, 'A non-empty error response can still represent a failed request.'], ['Remove the assertion for the id.', false, 'The status and useful body contract should both be verified.']] },
  { label: 'ACCESSIBILITY · SEMANTICS', title: 'A modal dialog opens, but keyboard users remain behind it.', error: 'Tab key moves to page navigation while the dialog is open', code: `<div class="modal">\n  <h2>Delete payment method?</h2>\n</div>`, choices: [['Use a semantic dialog and move focus into it when it opens.', true, `<dialog aria-labelledby="delete-title">\n  <h2 id="delete-title">Delete payment method?</h2>\n</dialog>`], ['Add a brighter border to the modal.', false, 'Visual styling does not address keyboard focus or dialog semantics.'], ['Disable every page link permanently.', false, 'Focus should be managed while the dialog is open, then returned after it closes.']] },
  { label: 'SQL · DATA VALIDATION', title: 'The report shows every customer as having an order.', error: 'Customers with no orders appear in the “ordered this month” report', code: `SELECT c.customer_name, o.order_id\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nWHERE o.created_at >= '2026-07-01';`, choices: [['Move the order-date condition into the JOIN when customers without orders must remain visible.', true, `SELECT c.customer_name, o.order_id\nFROM customers c\nLEFT JOIN orders o\n  ON c.id = o.customer_id\n AND o.created_at >= '2026-07-01';`], ['Replace LEFT JOIN with INNER JOIN.', false, 'That would intentionally remove customers without orders and make the report less complete.'], ['Remove the date condition entirely.', false, 'The reporting period still matters; the condition belongs where it preserves the intended join behavior.']] },
  { label: 'SQL · SAFE UPDATES', title: 'A data-fix script changes every customer’s status.', error: 'Unexpected row count: 42,718 records updated', code: `UPDATE customers\nSET status = 'inactive';`, choices: [['Use a specific WHERE clause and verify the target rows with SELECT first.', true, `SELECT customer_id, status\nFROM customers\nWHERE last_login_at < '2024-01-01';\n\nUPDATE customers\nSET status = 'inactive'\nWHERE last_login_at < '2024-01-01';`], ['Run the update again to confirm the result.', false, 'Repeating an unscoped update cannot validate or undo the damage.'], ['Add ORDER BY customer_id to the update.', false, 'Ordering does not limit which rows are changed. A clear predicate is required.']] },
] as const

export function FixCodeChallenges() {
  const [index, setIndex] = useState(0)
  const [answer, setAnswer] = useState<number | null>(null)
  const challenge = challenges[index]
  const [choiceOrder, setChoiceOrder] = useState(() => shuffle(challenge.choices.map((_, choiceIndex) => choiceIndex)))
  const isCorrect = answer !== null && challenge.choices[answer][1]
  const next = () => { const nextIndex = (index + 1) % challenges.length; setIndex(nextIndex); setChoiceOrder(shuffle(challenges[nextIndex].choices.map((_, choiceIndex) => choiceIndex))); setAnswer(null) }
  return <section className="fix-code"><div className="fix-code-heading"><p className="eyebrow">FIX THE CODE · {String(index + 1).padStart(2, '0')}/{String(challenges.length).padStart(2, '0')}</p><h2>{challenge.title}</h2><p>{challenge.label}</p></div><div className="fix-code-grid"><div className="code-problem"><p className="eyebrow">FAILING CHECK</p><pre><code>{challenge.code}</code></pre><p className="code-error">{challenge.error}</p></div><div className="code-choices"><p className="eyebrow">CHOOSE THE BEST FIX</p>{choiceOrder.map((choiceIndex, displayIndex) => { const [choice, correct, solution] = challenge.choices[choiceIndex]; return <button type="button" key={choice} className={answer === choiceIndex ? (correct ? 'correct' : 'incorrect') : ''} onClick={() => setAnswer(choiceIndex)}><span>{String.fromCharCode(65 + displayIndex)}</span><b>{choice}</b>{answer === choiceIndex && <small>{correct ? <>Best fix:<pre><code>{solution}</code></pre></> : solution}</small>}</button> })}{answer !== null && <button type="button" className="code-next" onClick={next}>{isCorrect ? 'Next challenge →' : 'Try another challenge →'}</button>}</div></div></section>
}
