import { useEffect, useState } from 'react'

type Guide = 'automation-ai' | 'test-design' | 'api-testing' | 'rag-training'

type ArticleDetail = { deepDive: string; example: string; pitfall: string }

const articleDetails: Record<Guide, Record<string, ArticleDetail>> = {
  'automation-ai': {
    'The distinction': { deepDive: 'Automation follows defined steps and compares an actual result with an expected result. AI is better at generating, summarizing, classifying, or helping you notice patterns. The distinction matters because a generated suggestion needs review, while a stable automated check should deliver repeatable evidence.', example: 'For a password reset flow, automation can confirm that a valid reset link changes the password. AI can help list edge cases—expired links, duplicate requests, or unclear error wording—for a tester to verify.', pitfall: 'Do not call a probabilistic AI response an automated test unless its expected behavior and evaluation method are defined.' },
    'Use automation': { deepDive: 'Good automation earns its place by producing timely, trustworthy feedback. Start where behavior is stable, test data can be controlled, and a failure would matter to a user or business process.', example: 'A checkout confirmation that runs on every release is a stronger first candidate than a design experiment that changes several times a week.', pitfall: 'Avoid automating a workflow only because it is repetitive; unstable setup and unclear expected behavior create noisy failures.' },
    'Use AI support': { deepDive: 'AI is most useful as a fast first draft. It can expand a requirement, suggest edge cases, summarize logs, or turn rough notes into a clearer test outline. Its output improves as you give it concrete product context.', example: 'Provide a story, acceptance criteria, user role, and known risk; then ask for the three highest-risk failure states and questions that need clarification.', pitfall: 'Never accept a generated test idea as product truth without checking it against the requirement and the system.' },
    'Keep humans central': { deepDive: 'Human testers connect behavior to intent. They notice confusing language, accessibility barriers, surprising workflows, and risk that does not fit a scripted path. That judgment becomes more important when a feature is new or ambiguous.', example: 'A script can confirm a dialog opens; a tester can notice that keyboard focus lands behind it and blocks someone from completing the task.', pitfall: 'Do not use fast feedback as an excuse to remove exploration, accessibility checks, or conversations with the team.' },
    'Combine them': { deepDive: 'The most useful workflow gives each capability the work it does best: people frame the problem and interpret impact, AI accelerates preparation, and automation repeats a known check consistently.', example: 'Before a release, use AI to draft risk questions, automate the stable smoke path, then have a tester explore new or changing behavior.', pitfall: 'A long toolchain is not automatically better; keep the loop simple enough that people can understand the evidence.' },
  },
  'test-design': {
    'Start with risk': { deepDive: 'Risk-based design starts with what could go wrong, who would be affected, and how likely or expensive that failure would be. It helps you choose the most valuable checks instead of treating every screen or input as equally important.', example: 'For an address change, incorrect data reaching a payment or identity process is more consequential than a minor alignment issue, so validate data handling first.', pitfall: 'Do not confuse risk with complexity. A simple, high-volume workflow can be the highest-risk part of a release.' },
    Boundaries: { deepDive: 'Boundaries are the edges of an allowed range. Defects often appear immediately below, at, and immediately above a minimum, maximum, date, count, or monetary limit because implementation rules change at those points.', example: 'If a field allows 1–50 characters, test 0, 1, 50, and 51 characters rather than many arbitrary valid values.', pitfall: 'A boundary check is only useful when the expected behavior is clear; confirm whether the limit includes spaces, formatting, or Unicode characters.' },
    Partitions: { deepDive: 'Equivalence partitioning groups inputs that should behave the same way. Instead of testing every valid age, for example, select one representative from each meaningful valid and invalid group.', example: 'For an age rule of 18–65, choose one value below 18, one within the range, and one above 65, then add separate boundary checks.', pitfall: 'Do not assume every value in a group behaves alike when business rules, formatting, or integrations treat values differently.' },
    Decisions: { deepDive: 'Decision tables make rule combinations visible. They are useful whenever an outcome depends on several conditions, such as role, account state, location, or approval status.', example: 'A refund may require both an eligible order and an authorized user. Listing all yes/no combinations exposes the denied paths that a happy path misses.', pitfall: 'Keep tables focused on the rules that change the outcome; adding every possible condition can hide the important combinations.' },
    'State changes': { deepDive: 'State transition testing follows the life of an item: created, pending, approved, cancelled, completed, and so on. The key question is not just what the screen shows, but which moves are valid from the current state.', example: 'A cancelled claim should not be paid without a permitted reopen path; test the attempted invalid transition as well as the valid one.', pitfall: 'Do not test each state in isolation. The route into the state can change what actions should be available.' },
    Pairwise: { deepDive: 'Pairwise testing reduces a large combination set by ensuring every pair of input values appears together at least once. It is efficient for compatible browsers, roles, settings, or data types.', example: 'For browser, role, language, and payment method, pairwise selection gives broad interaction coverage without testing every possible combination.', pitfall: 'Pairwise coverage does not replace intentionally testing known dangerous combinations, regulatory requirements, or historical defects.' },
  },
  'api-testing': {
    'Start here': { deepDive: 'An API is a contract between callers and a service. Testing it means confirming the request is understood, the response is accurate, and the side effect is safe—not simply seeing a successful-looking status.', example: 'A POST request that returns 201 should also create the intended record with correct fields and no duplicate side effect.', pitfall: 'Do not stop at the UI when a defect may live in the service, data, authentication, or integration layer.' },
    'Build requests': { deepDive: 'Requests contain several independent controls: method, route, headers, query parameters, and a body. Changing one at a time makes it easier to learn which rule is responsible for a response.', example: 'Send the same POST body with a missing authorization header, then with an invalid quantity, and compare the response and saved state.', pitfall: 'Do not vary multiple inputs at once when investigating; it becomes hard to tell which change caused the behavior.' },
    'Read responses': { deepDive: 'A response includes more than a status code. Headers may identify content type, caching, rate limits, or a newly created location; the body communicates the returned data and error details.', example: 'After creating an order, check the 201 status, returned order ID, status value, and whether the order appears in the follow-up retrieval.', pitfall: 'Do not expose internal errors or sensitive data in a response merely to make debugging easier.' },
    Validate: { deepDive: 'Schema and business validation work together. A schema checks structure and data types; business validation checks whether the values make sense in context and obey the product rules.', example: 'A response can have a correctly typed total but still be wrong if it includes a discount that the current customer is not eligible to receive.', pitfall: 'Avoid brittle tests that require every irrelevant field to appear in a fixed order or with a static timestamp.' },
    'Protect access': { deepDive: 'Authentication establishes identity. Authorization applies the permissions for that identity to a requested action or resource. Test missing, expired, altered, and cross-user credentials separately.', example: 'A regular user should receive a safe denial when requesting an admin report, and should not learn whether another user’s private record exists.', pitfall: 'Do not treat a 401 and 403 as interchangeable without understanding your service’s documented contract and security model.' },
    'Handle failure': { deepDive: 'Resilient services handle bad input, timeouts, duplicate messages, and dependency failures predictably. The goal is a useful and safe outcome, including when a caller retries after an uncertain result.', example: 'For a payment request, use an idempotency key and verify a retry does not create a second charge after a timeout.', pitfall: 'Do not test only clean errors; partial completion and delayed downstream responses often reveal more serious risks.' },
  },
  'rag-training': {
    'The idea': { deepDive: 'Retrieval-augmented generation gives an AI system relevant source material at the time it answers. The model still writes the response, but quality depends on whether it retrieved allowed, current, and useful evidence.', example: 'A benefits assistant can retrieve the current employee policy before answering a leave question instead of relying only on general model knowledge.', pitfall: 'RAG does not make an answer correct when the source is stale, incomplete, or unrelated to the question.' },
    'Prepare content': { deepDive: 'Source quality drives retrieval quality. Documents need clear ownership, dates, access labels, and focused sections so the system can identify what is relevant and whether a user should see it.', example: 'Split a long policy into topic-based chunks with a title, owner, audience, and last-reviewed date so a result can be inspected later.', pitfall: 'Do not index confidential or duplicate material without a defined access and retention approach.' },
    'Retrieve well': { deepDive: 'Retrieval should be evaluated before the answer. A fluent response may cite a plausible but irrelevant passage, so inspect which chunks were selected for different phrasings of the same intent.', example: 'Ask “How do I change benefits?” and “Can I update my plan?” then verify both retrieve the current enrollment guidance.', pitfall: 'Do not judge retrieval only by whether a response sounds confident; relevance and source access matter.' },
    'Ground answers': { deepDive: 'Grounding means an answer stays within the available evidence and distinguishes facts from uncertainty. Good systems can cite, summarize carefully, or say they do not have enough information.', example: 'When the source does not state a reimbursement amount, the assistant should not invent one; it can direct the user to the documented owner or process.', pitfall: 'Do not reward polished wording if it hides unsupported claims or omits an important limitation.' },
    'Test risks': { deepDive: 'RAG adds risks beyond ordinary chat: stale content, permission leaks, instruction-like text inside a document, poor retrieval, and unsafe fallback behavior when evidence is missing.', example: 'Test a restricted policy with an unauthorized user and verify it is neither retrieved nor indirectly summarized in the answer.', pitfall: 'Do not test only normal questions. Include adversarial, ambiguous, outdated, and access-controlled scenarios.' },
    Evaluate: { deepDive: 'Evaluation turns subjective quality into repeatable evidence. A small, representative question set should define what relevance, grounding, completeness, and safe behavior look like before a release.', example: 'For each test question, record the expected source, acceptable answer elements, unacceptable claims, and whether a human review is required.', pitfall: 'Do not rely on one overall score; a system can be fluent while failing the criteria that matter most to users.' },
  },
}

export function GuideLessonArticle({ guide, lesson, title, copy, points }: { guide: Guide; lesson: string; title: string; copy: string; points: string[] }) {
  const [isOpen, setIsOpen] = useState(false)
  const detail = articleDetails[guide][lesson]

  useEffect(() => {
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setIsOpen(false) }
    window.addEventListener('keydown', closeOnEscape)
    return () => window.removeEventListener('keydown', closeOnEscape)
  }, [])

  if (!detail) return null
  return <><button type="button" className="guide-article-link" onClick={() => setIsOpen(true)}>Read full article <span aria-hidden="true">↗</span></button>{isOpen && <div className="guide-article-overlay" role="presentation" onMouseDown={() => setIsOpen(false)}><article className="guide-article-dialog" role="dialog" aria-modal="true" aria-labelledby="guide-article-title" onMouseDown={(event) => event.stopPropagation()}><button type="button" className="guide-article-close" onClick={() => setIsOpen(false)} aria-label="Close article">×</button><p className="eyebrow">{guide.replace('-', ' ').toUpperCase()} · FULL ARTICLE</p><h2 id="guide-article-title">{title}</h2><p className="guide-article-lead">{copy}</p><section><p className="eyebrow">WHY IT MATTERS</p><p>{detail.deepDive}</p></section><section><p className="eyebrow">IN PRACTICE</p><p>{detail.example}</p><ul>{points.map((point) => <li key={point}>{point}</li>)}</ul></section><section><p className="eyebrow">COMMON PITFALL</p><p>{detail.pitfall}</p></section><button type="button" className="guide-article-return" onClick={() => setIsOpen(false)}>Back to lesson ↑</button></article></div>}</>
}
