import { useMemo, useState } from 'react'

const promptLibrary = [
  { category: 'Requirements', label: 'Requirement review', when: 'Use before testing begins.', paste: 'Paste a user story, acceptance criteria, or feature notes.', outcome: 'A list of assumptions, missing criteria, risks, and questions.', prompt: 'Act as a QA engineer reviewing this requirement: [PASTE REQUIREMENT]. Identify unclear acceptance criteria, assumptions, user risks, edge cases, accessibility considerations, integration concerns, and the most useful questions to clarify before testing. Return the findings in priority order.' },
  { category: 'Requirements', label: 'Acceptance criteria helper', when: 'Use when a story is too broad to test confidently.', paste: 'Paste the story and any known business rules.', outcome: 'Clear, testable acceptance criteria and open questions.', prompt: 'Turn this feature request into testable acceptance criteria: [PASTE STORY]. Include the intended user outcome, happy path, important failure states, permissions or data conditions, accessibility expectations, and questions that still need product clarification. Do not invent product rules; label assumptions clearly.' },
  { category: 'Test design', label: 'Risk-based test plan', when: 'Use when planning coverage for a feature or release.', paste: 'Paste the feature, user types, and known changes.', outcome: 'Prioritized coverage, risks, and a starting test approach.', prompt: 'Act as a senior QA engineer. Based on this feature: [PASTE FEATURE], create a risk-based test approach. Include the highest-risk user journeys, happy paths, negative paths, boundary cases, data needs, accessibility checks, API or integration concerns, and questions to clarify. Prioritize the list by user and business impact.' },
  { category: 'Test design', label: 'Exploratory test charter', when: 'Use before a focused exploratory session.', paste: 'Paste the feature, change, or user problem to explore.', outcome: 'A time-boxed mission, ideas to investigate, and evidence to capture.', prompt: 'Create a 45-minute exploratory testing charter for: [PASTE FEATURE OR CHANGE]. Provide a clear mission, the user or risk to focus on, test ideas to explore, useful data or environments, and the evidence to capture. Keep the plan focused enough for one session.' },
  { category: 'Automation', label: 'Automation candidate check', when: 'Use when deciding whether to automate a workflow.', paste: 'Paste the workflow, frequency, risk, and known setup needs.', outcome: 'A recommendation with trade-offs and a small first automation step.', prompt: 'Evaluate whether this workflow is a good automation candidate: [PASTE WORKFLOW]. Consider repetition, business or user risk, behavior stability, test data, setup complexity, maintenance cost, and feedback value. Recommend automate, explore manually, or use a blended approach. Explain the first useful step without promising unrealistic coverage.' },
  { category: 'Automation', label: 'Automation test outline', when: 'Use before writing a Playwright, Selenium, or REST Assured test.', paste: 'Paste the user journey or API behavior and chosen tool.', outcome: 'Readable test intent, setup, assertions, and reliability concerns.', prompt: 'Outline a maintainable automated test for [PASTE JOURNEY OR API] using [PLAYWRIGHT / SELENIUM / REST ASSURED]. Include test intent, preconditions, stable test data, key actions, meaningful assertions, cleanup, failure diagnostics, and likely sources of flakiness. Do not write production code unless requested.' },
  { category: 'API testing', label: 'API coverage ideas', when: 'Use when learning or expanding an endpoint test plan.', paste: 'Paste the endpoint, method, expected contract, and auth details.', outcome: 'Request, response, validation, and failure coverage ideas.', prompt: 'Create API test ideas for: [METHOD AND ENDPOINT]. Context: [PASTE CONTRACT, AUTH, AND BUSINESS RULES]. Include valid requests, required and optional fields, invalid or boundary data, authentication and authorization, response schema, error handling, idempotency or duplicate requests where relevant, and dependency failures. Separate must-have checks from useful follow-ups.' },
  { category: 'API testing', label: 'API defect investigation', when: 'Use after an unexpected response or integration failure.', paste: 'Paste the request, response, environment, and observed behavior.', outcome: 'A disciplined list of checks and evidence—not guesses.', prompt: 'Help investigate this API issue without guessing. Request: [PASTE REQUEST]. Response or error: [PASTE RESPONSE]. Environment and context: [PASTE DETAILS]. Suggest the most useful next checks involving inputs, authentication, headers, logs, downstream services, data state, and comparison environments. State what evidence would confirm each likely cause.' },
  { category: 'Accessibility', label: 'Accessible flow checklist', when: 'Use while testing a workflow with forms, dialogs, or status changes.', paste: 'Paste the user flow and main UI elements.', outcome: 'Keyboard, focus, labels, errors, and status checks.', prompt: 'Create a practical accessibility test checklist for this flow: [PASTE FLOW]. Cover keyboard-only use, focus order and visible focus, semantic labels, form errors, dialogs, status messages, color or contrast risks, zoom and responsive behavior, and what to verify with assistive technology. Keep the checklist focused on observable behavior.' },
  { category: 'Accessibility', label: 'Accessibility defect helper', when: 'Use when documenting an accessibility issue clearly.', paste: 'Paste what happened, expected behavior, and the environment.', outcome: 'A respectful, reproducible defect report with impact.', prompt: 'Turn these notes into a clear accessibility defect report: [PASTE NOTES]. Include a concise title, environment, reproduction steps, actual and expected behavior, likely user impact, relevant accessibility context, and evidence to attach. Avoid claiming a formal compliance violation unless the supplied evidence supports it.' },
  { category: 'Delivery', label: 'Release readiness', when: 'Use before a release or a high-risk production change.', paste: 'Paste the release scope, changes, and known risks.', outcome: 'A concise readiness conversation and follow-up plan.', prompt: 'Create a concise release-readiness checklist for: [PASTE FEATURE OR RELEASE]. Include functional coverage, regression risk, integrations, accessibility, known gaps, monitoring, support ownership, rollback or recovery considerations, and stakeholder communication. Separate release blockers from follow-up work.' },
  { category: 'Delivery', label: 'AI feature evaluation', when: 'Use when testing an LLM-powered feature or assistant.', paste: 'Paste the feature goal, intended audience, and any guardrails.', outcome: 'A starting evaluation set for usefulness, safety, and reliability.', prompt: 'Create a QA evaluation plan for this AI feature: [PASTE FEATURE AND GUARDRAILS]. Include representative user questions, ambiguous requests, harmful or irrelevant requests, prompt-injection attempts, incorrect or unsupported answers, privacy concerns, consistency checks, escalation behavior, and criteria for human review. Treat the output as a test starting point, not a safety guarantee.' },
] as const

const promptCategories = ['All', ...Array.from(new Set(promptLibrary.map((item) => item.category)))]

type TestIdea = { label: string; text: string }

function buildTestIdeas(description: string): TestIdea[] {
  const featureName = description.replace(/\s+/g, ' ').trim().replace(/[.?!]+$/, '').slice(0, 120) || 'this feature'
  const normalized = description.toLowerCase()
  const ideas: TestIdea[] = [
    { label: 'Core journey', text: `Verify that a user can complete “${featureName}” with valid data and receives a clear success state.` },
    { label: 'Validation', text: `Identify the required information and test missing, malformed, duplicate, and boundary-value input for “${featureName}.”` },
    { label: 'Recovery', text: `Interrupt the flow with a refresh, back navigation, timeout, or repeat attempt. Confirm that “${featureName}” handles recovery without lost, duplicated, or misleading data.` },
    { label: 'Accessibility', text: `Complete “${featureName}” using only a keyboard. Check focus order, labels, error messaging, and status updates.` },
  ]

  if (/(password|login|sign in|authentication|account)/.test(normalized)) {
    ideas.push({ label: 'Account safety', text: 'Check expired or reused links, invalid credentials, lockout behavior, session changes, and whether sensitive details stay hidden.' })
  } else if (/(payment|checkout|order|purchase|invoice|cart)/.test(normalized)) {
    ideas.push({ label: 'Transaction integrity', text: 'Check amounts, tax or discounts, failed payments, duplicate submission, confirmation details, and the resulting order state.' })
  } else if (/(email|notification|message|alert)/.test(normalized)) {
    ideas.push({ label: 'Delivery and content', text: 'Check who receives the message, timing, duplicate sends, content accuracy, links, and behavior when delivery fails.' })
  } else if (/(upload|file|attachment|document|image)/.test(normalized)) {
    ideas.push({ label: 'File handling', text: 'Check supported formats, empty or oversized files, interrupted uploads, duplicate files, progress feedback, and safe error recovery.' })
  } else if (/(search|filter|sort|list|dashboard)/.test(normalized)) {
    ideas.push({ label: 'Data behavior', text: 'Check empty results, partial matches, special characters, pagination, sorting consistency, and whether filters persist when the user returns.' })
  } else {
    ideas.push({ label: 'Dependencies', text: `List the APIs, permissions, emails, or saved data that support “${featureName}.” Test success, delay, and failure responses for each.` })
  }

  return ideas
}

export function QaToolkits() {
  const [activeTool, setActiveTool] = useState<'decision' | 'cases' | 'prompts'>('decision')
  const [answers, setAnswers] = useState([false, false, false, false])
  const [feature, setFeature] = useState('')
  const [showCases, setShowCases] = useState(false)
  const [copied, setCopied] = useState<string | null>(null)
  const [promptCategory, setPromptCategory] = useState('All')
  const score = answers.filter(Boolean).length
  const recommendation = useMemo(() => score >= 3 ? ['Good automation candidate', 'This flow looks repeatable, high-value, and stable enough to automate. Start with the most important path, then add coverage deliberately.'] : score === 2 ? ['Use a blended approach', 'Automate the stable, repeatable parts of this flow. Pair it with exploratory testing until the experience or risk is clearer.'] : ['Explore before you automate', 'Focus on understanding the behavior, risks, and change rate first. Automation will be more useful once the workflow is stable and understood.'], [score])
  const copyPrompt = async (label: string, text: string) => {
    await navigator.clipboard?.writeText(text)
    setCopied(label)
    window.setTimeout(() => setCopied(null), 1800)
  }
  const checklist = feature.trim() || 'this feature'
  const testIdeas = useMemo(() => buildTestIdeas(checklist), [checklist])
  const visiblePrompts = useMemo(() => promptCategory === 'All' ? promptLibrary : promptLibrary.filter((item) => item.category === promptCategory), [promptCategory])

  return <section className="toolkits section" id="tools">
    <div className="section-heading"><p className="eyebrow">QA TOOLKITS</p><h2>Useful tools.<br /><em>No fluff.</em></h2><p className="section-copy">Simple helpers for making better testing decisions before you open a ticket, write a script, or start a release.</p></div>
    <div className="tool-tabs" role="tablist" aria-label="QA tools"><button type="button" className={activeTool === 'decision' ? 'active' : ''} onClick={() => setActiveTool('decision')} role="tab" aria-selected={activeTool === 'decision'}>Automation guide</button><button type="button" className={activeTool === 'cases' ? 'active' : ''} onClick={() => setActiveTool('cases')} role="tab" aria-selected={activeTool === 'cases'}>Test case starter</button><button type="button" className={activeTool === 'prompts' ? 'active' : ''} onClick={() => setActiveTool('prompts')} role="tab" aria-selected={activeTool === 'prompts'}>QA prompts</button></div>

    {activeTool === 'decision' && <div className="tool-panel"><div className="tool-panel-copy"><p className="eyebrow">AUTOMATION DECISION GUIDE</p><h3>Should this be automated?</h3><p>Answer four practical questions. This is a starting conversation—not a substitute for understanding the product.</p></div><div className="decision-card"><div className="decision-questions">{['Does the flow happen often or on every release?', 'Would a failure create meaningful user or business risk?', 'Is the expected behavior stable enough to describe clearly?', 'Can the test run without complex, fragile setup?'].map((question, index) => <label key={question}><input type="checkbox" checked={answers[index]} onChange={() => setAnswers(answers.map((answer, answerIndex) => answerIndex === index ? !answer : answer))} /><span>{question}</span><i>{answers[index] ? '✓' : '+'}</i></label>)}</div><div className="decision-result"><p className="eyebrow">RECOMMENDATION · {score}/4 SIGNALS</p><h4>{recommendation[0]}</h4><p>{recommendation[1]}</p></div></div></div>}

    {activeTool === 'cases' && <div className="tool-panel"><div className="tool-panel-copy"><p className="eyebrow">TEST CASE STARTER</p><h3>Turn a feature into test ideas.</h3><p>Describe the feature or user story. You’ll get a practical checklist to begin your own test design.</p></div><div className="case-card"><label htmlFor="feature">FEATURE OR USER STORY</label><textarea id="feature" value={feature} onChange={(event) => { setFeature(event.target.value); setShowCases(false) }} placeholder="Example: A customer can reset their password using an email link." /><button type="button" className="button primary" onClick={() => setShowCases(true)}>Generate test ideas <span aria-hidden="true">↗</span></button>{showCases && <div className="case-results"><p className="eyebrow">STARTER CHECKLIST FOR {checklist.toUpperCase()}</p><ul>{testIdeas.map((idea) => <li key={idea.label}><b>{idea.label}:</b> {idea.text}</li>)}</ul></div>}</div></div>}

    {activeTool === 'prompts' && <div className="tool-panel"><div className="tool-panel-copy"><p className="eyebrow">QA PROMPT LIBRARY</p><h3>Prompts that improve the work.</h3><p>Choose a real QA moment, add your product context, and review the output before you rely on it.</p></div><div><div className="prompt-filters" role="group" aria-label="Filter QA prompts by category">{promptCategories.map((category) => <button type="button" key={category} className={promptCategory === category ? 'active' : ''} onClick={() => setPromptCategory(category)} aria-pressed={promptCategory === category}>{category}</button>)}</div><p className="prompt-swipe-hint">Swipe or scroll to explore {visiblePrompts.length} prompts <span aria-hidden="true">→</span></p><div className="prompt-list-tool">{visiblePrompts.map((item) => <article key={item.label}><p>{item.category} · {item.label}</p><div className="prompt-meta"><span><b>When to use</b>{item.when}</span><span><b>Paste in</b>{item.paste}</span><span><b>You’ll get</b>{item.outcome}</span></div><pre>{item.prompt}</pre><button type="button" onClick={() => copyPrompt(item.label, item.prompt)}>{copied === item.label ? 'Copied ✓' : 'Copy prompt ↗'}</button></article>)}</div></div></div>}
  </section>
}
