import { useState } from 'react'
import { Logo } from './Logo'
import { ThemeToggle } from './ThemeToggle'

type Lesson = {
  number: string
  label: string
  title: string
  copy: string
  points: string[]
  example: Array<{ label: string; value: string; hint: string }>
}

const lessons: Lesson[] = [
  { number: '01', label: 'The idea', title: 'RAG gives an AI relevant source material.', copy: 'Retrieval-augmented generation (RAG) first finds useful content, then gives that content to an AI model before it writes an answer. It helps the model answer from your approved knowledge instead of relying only on general training.', points: ['Knowledge lives in documents, articles, policies, or records.', 'A retrieval step selects relevant passages.', 'The model answers using those passages as context.'], example: [{ label: 'question', value: '“What is our refund policy?”', hint: 'The user asks a question.' }, { label: 'retrieve', value: 'Find passages about refunds and return windows.', hint: 'The system finds relevant source content.' }, { label: 'answer', value: 'Respond using the retrieved policy and cite it when possible.', hint: 'The model generates an answer grounded in the source.' }] },
  { number: '02', label: 'Prepare content', title: 'Good answers start with good source material.', copy: 'Before retrieval can work well, content needs to be accurate, current, organized, and safe to share. RAG cannot reliably correct contradictory or outdated documentation on its own.', points: ['Use a clear owner and review date for each source.', 'Remove duplicate and obsolete content.', 'Separate public information from sensitive content.'], example: [{ label: 'source', value: 'Refund policy · reviewed July 2026', hint: 'A source should have a clear owner and review date.' }, { label: 'chunk', value: '“Returns are accepted within 30 days…”', hint: 'A chunk is a focused piece of source content.' }, { label: 'metadata', value: 'audience: customer · region: US', hint: 'Metadata helps retrieval choose the right content.' }] },
  { number: '03', label: 'Retrieve well', title: 'The right context matters more than more context.', copy: 'A retrieval system should return the most useful evidence, not every loosely related document. Too little context causes gaps; too much context can distract the model or introduce conflicting instructions.', points: ['Test exact, vague, and differently worded questions.', 'Check results across regions, roles, and product versions.', 'Inspect the source passages returned before judging the answer.'], example: [{ label: 'query', value: '“Can I return a sale item?”', hint: 'A realistic question to retrieve against.' }, { label: 'top result', value: 'Sale-item exceptions · customer policy', hint: 'The highest-ranked source returned.' }, { label: 'check', value: 'Relevant, current, authorized, and complete?', hint: 'The QA review questions for retrieved context.' }] },
  { number: '04', label: 'Ground answers', title: 'An answer should stay connected to its evidence.', copy: 'Grounded answers reflect what the retrieved source actually says. A strong RAG experience makes uncertainty visible instead of inventing details when evidence is missing or conflicting.', points: ['Compare claims in the answer to its cited source.', 'Test questions with no matching documentation.', 'Require a safe fallback when evidence is insufficient.'], example: [{ label: 'evidence', value: '“Returns accepted within 30 days with receipt.”', hint: 'The source passage the answer can rely on.' }, { label: 'answer', value: '“You can return it within 30 days with a receipt.”', hint: 'A grounded answer that mirrors the evidence.' }, { label: 'fallback', value: '“I could not find a policy for that case.”', hint: 'A safe response when evidence is unavailable.' }] },
  { number: '05', label: 'Test risks', title: 'RAG testing includes safety, access, and failure behavior.', copy: 'Test the system as both a search experience and an AI experience. A polished answer is not successful if it leaks private content, follows malicious text from a document, or uses an out-of-date rule.', points: ['Verify role-based access to sources and answers.', 'Test prompt-injection text inside uploaded documents.', 'Check stale, conflicting, and missing sources.'], example: [{ label: 'role', value: 'Customer user requests internal operations policy.', hint: 'Access control test.' }, { label: 'expected', value: 'No internal content is retrieved or exposed.', hint: 'Safe expected behavior.' }, { label: 'audit', value: 'Log source IDs, access decision, and fallback reason.', hint: 'Evidence useful for investigation.' }] },
  { number: '06', label: 'Evaluate', title: 'Measure usefulness, not just fluent writing.', copy: 'Evaluation connects RAG behavior to real user needs. Use a representative question set, define what a good answer needs, and review both retrieval quality and answer quality over time.', points: ['Create a small, reviewed set of real questions.', 'Score relevance, grounding, completeness, and safety.', 'Track regressions when sources or retrieval settings change.'], example: [{ label: 'test set', value: '50 reviewed questions across common user tasks', hint: 'A stable evaluation set.' }, { label: 'metrics', value: 'Retrieval relevance · groundedness · safe fallback rate', hint: 'Measures that reveal where the system is weak.' }, { label: 'release', value: 'Compare the new version against the baseline.', hint: 'Use evaluations before releasing changes.' }] },
]

export function RagTrainingGuide({ onBack, theme, onToggleTheme }: { onBack: () => void; theme: 'light' | 'dark'; onToggleTheme: () => void }) {
  const [activeIndex, setActiveIndex] = useState(0)
  const lesson = lessons[activeIndex]

  return <main className="api-guide-hub rag-guide-hub" id="top" tabIndex={-1}>
    <header className="learn-hub-nav"><Logo onHome={onBack} /><div className="hub-nav-actions"><ThemeToggle theme={theme} onToggle={onToggleTheme} /><button type="button" onClick={onBack}>← Back to Learn</button></div></header>
    <section className="api-guide-hero"><p className="eyebrow">RAG TRAINING</p><h1>Make AI answers<br /><em>evidence-led.</em></h1><p>A practical introduction to retrieval-augmented generation for QA: source quality, retrieval, grounded answers, safety, and evaluation.</p></section>
    <section className="api-guide-main" aria-label="RAG training lessons"><aside className="api-guide-tabs" role="tablist" aria-label="RAG training topics">{lessons.map((item, index) => <button type="button" key={item.label} className={activeIndex === index ? 'active' : ''} onClick={() => setActiveIndex(index)} role="tab" aria-selected={activeIndex === index}><span>{item.number}</span>{item.label}<b>↗</b></button>)}</aside><article className="api-guide-lesson" aria-live="polite"><p className="eyebrow">{lesson.number} · {lesson.label.toUpperCase()}</p><h2>{lesson.title}</h2><p>{lesson.copy}</p><ul>{lesson.points.map((point) => <li key={point}>{point}</li>)}</ul><div className="api-guide-example"><div className="api-example-heading"><p className="eyebrow">EXAMPLE FLOW</p><span>Hover a line for context.</span></div>{lesson.example.map((line) => <code key={line.value} title={line.hint}><span>{line.label}</span>{line.value}</code>)}</div><div className="api-guide-controls"><button type="button" disabled={activeIndex === 0} onClick={() => setActiveIndex((index) => index - 1)}>← Previous</button><button type="button" disabled={activeIndex === lessons.length - 1} onClick={() => setActiveIndex((index) => index + 1)}>Next lesson →</button></div></article></section>
    <section className="api-guide-checklist"><p className="eyebrow">RAG QA CHECKLIST</p><h2>Before releasing a RAG feature,<br /><em>test the evidence path.</em></h2><div>{['Can this user access every source used in the answer?', 'Are the returned passages relevant, current, and complete?', 'Does the answer make claims that the evidence supports?', 'Does the system fail safely when it cannot find enough evidence?'].map((item, index) => <p key={item}><span>{String(index + 1).padStart(2, '0')}</span>{item}</p>)}</div></section>
  </main>
}
