import { Logo } from './Logo'
import { ThemeToggle } from './ThemeToggle'
import { PageDetails } from './PageDetails'

type StoryHubProps = { onClose: () => void; onOpenLearn: () => void; onOpenTools: () => void; theme: 'light' | 'dark'; onToggleTheme: () => void }

export function StoryHub({ onClose, onOpenLearn, onOpenTools, theme, onToggleTheme }: StoryHubProps) {
  return <main className="story-hub" id="top" tabIndex={-1}>
    <header className="learn-hub-nav"><Logo onHome={onClose} /><div className="hub-nav-actions"><ThemeToggle theme={theme} onToggle={onToggleTheme} /><button type="button" onClick={onClose}>← Back to home</button></div></header>
    <section className="story-hero"><p className="eyebrow">MY STORY</p><h1>Quality work is<br />about <em>people.</em></h1><p>it’s Wattϟ is built by Derrick Watson - a QA professional focused on practical quality engineering, thoughtful automation, and AI workflows that help teams build software people can trust.</p></section>
    <PageDetails title="The experiences behind the learning hub." summary="This page connects Derrick’s operations background, return to IT, and QA practice to the values behind it’s Wattϟ." items={['Start with the operations foundation that shaped a people-first quality mindset.', 'Read the QA journey and the opportunity that opened the door.', 'Use the mission section to jump into Learn or QA Toolkits.']} />

    <section className="story-section"><div className="story-split"><p className="eyebrow">WHERE IT STARTED</p><div><h2>Operations taught me<br />how work really<br /><em>gets done.</em></h2><p>Before moving into QA, Derrick led daily retail operations: hiring, scheduling, training, and coaching a team of more than 15 people. That experience built a lasting respect for the people behind every process, handoff, and customer experience.</p><p>It still shapes the way he approaches quality today - with clear communication, useful documentation, and a focus on the real-world impact of software behavior.</p></div></div></section>

    <section className="story-section story-now"><div className="story-split"><p className="eyebrow">THE QA JOURNEY</p><div><h2>Curiosity became a<br /><em>quality practice.</em></h2><p>After being away from IT for more than 10 years following college, Derrick made a memorable impression on a QA manager who gave him an opportunity to step into the field. That chance became the start of a career built through consistency, curiosity, and a commitment to keep learning.</p><p>Over more than eight years in cross-functional QA delivery, Derrick has supported enterprise and regulatory platforms through functional testing, regression cycles, user acceptance testing, production validation, accessibility checks, and automation coverage.</p><div className="story-points"><article><span>QUALITY</span><h3>Start early</h3><p>Better outcomes come from asking useful questions in discovery and requirements - not just finding issues at the end.</p></article><article><span>AUTOMATION</span><h3>Keep it purposeful</h3><p>Automation should deliver clear feedback on meaningful risk, not create a fragile list of checks.</p></article><article><span>AI</span><h3>Use it thoughtfully</h3><p>AI can accelerate test ideas, documentation, and investigation while human judgment stays responsible for quality decisions.</p></article></div></div></div></section>

    <section className="story-section story-mission"><p className="eyebrow">WHY IT’S WATTϟ EXISTS</p><h2>Good QA learning should<br />feel <em>useful, not distant.</em></h2><p>it’s Wattϟ turns real quality-engineering habits into approachable lessons, tools, and starting points. The goal is simple: help people build confidence through practice, share what they learn, and contribute to software that earns trust.</p><div><button type="button" onClick={onOpenLearn}>Explore Learn <span>↗</span></button><button type="button" onClick={onOpenTools}>Try the QA Toolkits <span>↗</span></button><a href="https://www.linkedin.com/in/derrick-watson-watson/" target="_blank" rel="noreferrer">Connect on LinkedIn <span>↗</span></a></div></section>
  </main>
}
